name: bson
version: 0.3.4

description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/mongo-dart/bson
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  fixnum: ^0.10.8
  more: ^2.8.0
  rational: ^0.3.8

dev_dependencies:
  test: "^1.10.0"
