name: bson
version: 0.3.3
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ad van der Veer <advanderveer@gmail.com>
description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/vadimtsushko/bson
environment:
  sdk: '>=2.0.0-dev.69.2 <3.0.0'
dependencies:
  fixnum: '^0.10.8'
  more: '^1.9.2'
dev_dependencies:
  #browser: '^0.10.0+3'
  test: '^1.3.0'
  #dart_coveralls: '^0.6.0+1'
