name: bson
description: Bson library for Dart programming language
version: 0.1.0
authors: 
 - Vadim Tsushko <vadimtsushko@gmail.com>
 - Ad van der Veer <advanderveer@gmail.com>
homepage: https://github.com/vadimtsushko/bson_dart
dev_dependencies:
  unittest: any 
  browser: any 