name: bson
version: 0.3.3
authors:
- Vadim Tsushko <vadimtsushko@gmail.com>
- Ad van der Veer <advanderveer@gmail.com>
description: Bson library for Dart programming language. BSON, short for Binary JSON, is a binary-encoded serialization of JSON-like documents.
homepage: https://github.com/vadimtsushko/bson

environment:
  sdk: '>=2.10.0-2.0.dev <3.0.0'

dependencies:
  fixnum: ^0.10.11
  more: ^2.6.0

dev_dependencies:
  test: ^1.16.0-nullsafety.1
  pedantic: ^1.10.0-nullsafety
